#### MAKE A SAMPLE DOCKER-COMPOSE
version: "2.1"
services:
  app:
    build: ./go-app
    environment:
      DATABASE_HOST:  db
      DATABASE_NAME: dbname # CHANGE THIS.  Database name must match POSTGRES_DB
      DATABASE_USER: dbuser # CHANGE THIS.  Database user must match POSTGRES_USER. 
      DATABASE_PASSWORD: dbpassword # CHANGE THIS.  Database password must match POSTGRES_PASSWORD
      DATABASE_PORT: 5432
      WEB_HOST: 
      WEB_PORT: 3000
      API_Key: apikey # CHANGE THIS.  Get your API Key from https://developers.themoviedb.org/3
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: healthcheck/postgres:alpine 
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dbuser # CHANGE THIS. POSTGRES_USER is the username used to access postgres db 
      POSTGRES_PASSWORD: dbpassword # CHANGE THIS. POSTGRES_PASSWORD is the password used to access postgres db
      POSTGRES_DB: dbname # CHANGE THIS. POSTGRES_DB is the name of the database to store your data
    ports:
      - 5432:5432

  angular-app:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 4200:4200
    
