#### MAKE A SAMPLE DOCKER-COMPOSE
version: "2.1"
services:
  app:
    build: ./go-app
    environment:
      DATABASE_NAME: mycinema
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: secret
      DATABASE_PORT: 5432
      WEB_HOST: 
      WEB_PORT: 8080
    ports:
      - 3000:8080
    depends_on:
      db:
        condition: service_healthy
  db:
    image: healthcheck/postgres:alpine 
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mycinema
    ports:
      - 5432:5432

  angular-app:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 4200:4200
    
